name: digital_card
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_hooks: ^0.20.1
  awesome_bottom_bar: ^1.2.4
  flutter_slidable: ^3.0.0
  http: ^1.1.0
  intl: ^0.18.1
  get: ^4.6.6 
  socket_io_client: ^2.0.3+1
  carousel_slider: ^4.2.1
  hooks_riverpod: ^2.4.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  slidable_button: ^3.0.0+1
  salomon_bottom_bar: ^3.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts: 
    - family: Harlowsi
      fonts:
          - asset: fonts/HARLOWSI.ttf
    - family: PlayFairDisplay
      fonts:
          - asset: fonts/PlayfairDisplay-VariableFont_wght.ttf
    - family: DelaGothicOne
      fonts:
          - asset: fonts/DelaGothicOne-Regular.ttf
    - family: MartianMono
      fonts:
          - asset: fonts/MartianMono-VariableFont_wdth.ttf
    - family: LilitaOne
      fonts:
          - asset: fonts/LilitaOne-Regular.ttf
    - family: McLaren-Regular
      fonts:
          - asset: fonts/McLaren-Regular.ttf
    - family: MartianMono-VariableFont_wdth600
      fonts:
          - asset: fonts/MartianMono-VariableFont_wdth600.ttf
    - family: Roboto-Regular
      fonts:
          - asset: fonts/Roboto-Regular.ttf
    - family: Montserrat-Bold
      fonts:
          - asset: fonts/Montserrat-Bold.ttf
    
